// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2ncSo9i3q6U5haoUh1r-n-pThiIm_liU',
    appId: '1:548031148190:web:21bbc38b94713004160b8f',
    messagingSenderId: '548031148190',
    projectId: 'practice-2eefc',
    authDomain: 'practice-2eefc.firebaseapp.com',
    storageBucket: 'practice-2eefc.firebasestorage.app',
    measurementId: 'G-LWK3HL0MEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFkhFpNi55HcZSWJlFR8Rb1ebmB1v8Wrg',
    appId: '1:548031148190:android:07e8275547738a27160b8f',
    messagingSenderId: '548031148190',
    projectId: 'practice-2eefc',
    storageBucket: 'practice-2eefc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7HH08Z5AJGpM0DPBFIyWQh0VpCpKIZ3A',
    appId: '1:548031148190:ios:b21d7c8e0236dc50160b8f',
    messagingSenderId: '548031148190',
    projectId: 'practice-2eefc',
    storageBucket: 'practice-2eefc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseActivity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7HH08Z5AJGpM0DPBFIyWQh0VpCpKIZ3A',
    appId: '1:548031148190:ios:b21d7c8e0236dc50160b8f',
    messagingSenderId: '548031148190',
    projectId: 'practice-2eefc',
    storageBucket: 'practice-2eefc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseActivity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2ncSo9i3q6U5haoUh1r-n-pThiIm_liU',
    appId: '1:548031148190:web:ef90691f61395b71160b8f',
    messagingSenderId: '548031148190',
    projectId: 'practice-2eefc',
    authDomain: 'practice-2eefc.firebaseapp.com',
    storageBucket: 'practice-2eefc.firebasestorage.app',
    measurementId: 'G-6CC1KS40TD',
  );
}
